### ISSUE TITLE
IDSL.IPA computations successful but workflow stopped due to an error 

### ISSUE THREAD

**Issue by jasminesychong** [idslme/IDSL.IPA#5]
Hello,

I was able to successfully run IDSL.IPA (I believe so anyhow) on my 12 mzML files, however the command ended due to an error. Here's the end of the log

```
Completed gap-filling!
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
The required processing time was `1.21609768807888 hours`
2023-03-23 22:33:11 Etc/UTC


Completed IDSL.IPA computations successfully!
===================================================================================================
Error in base::try(ms1, silent = TRUE) : object 'ms1' not found

Stopped IDSL.IPA workflow!
```

Should the error be disregarded? 

Also, which output in the peak_alignment folder should be used as the peak table? peak_R13C_gapfilled.csv? 

Thank you!

**Comment by sajfb** [comment]
1) When you see `Completed IDSL.IPA computations successfully!`, your run is complete. The error message likely originated in R itself and does not affect IDSL.IPA.
2) You should see aligned tables for peak heights, peak areas, and R13C. R13C represents the ratio of 13C to 12C, which is a factor of the carbon counts in the compound that generated the chromatographic peak. In the manuscript, I discussed that consistency of R13C across samples for a peak can be used as a measure of detection accuracy.
3) gap-filled tables are also generated to fill gaps in the aligned tables for peaks that had low quality to pass IDSL.IPA peak detection criteria.
